#!/bin/sh
# Generated by the agent harness. Blocks commands per policy.
input=$(cat)
case "$input" in *"gh pr merge"*) printf '%s' '{"permission":"deny","agent_message":"Blocked by harness policy: The maintainer owns merges; agents stop at the open PR (use `land`, run by a human)."}'; exit 0;; esac
case "$input" in *"git push --force"*) printf '%s' '{"permission":"ask","user_message":"Force-push is destructive; confirm before rewriting remote history."}'; exit 0;; esac
printf '%s' '{"permission":"allow"}'
